/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FORMS;

/**
 *
 * @author Geovani
 */
public class PANTALLA_INICIAL extends javax.swing.JFrame {

    /**
     * Creates new form PANTALLA_INICIAL
     */
    public PANTALLA_INICIAL() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuEmpleados = new javax.swing.JMenuItem();
        jMenuClientes = new javax.swing.JMenuItem();
        jMenuCatalogos = new javax.swing.JMenu();
        jMenuDvd = new javax.swing.JMenuItem();
        jMenuVideos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );

        jMenu1.setText("INGRESO");

        jMenuEmpleados.setText("EMPLEADOS");
        jMenuEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEmpleadosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuEmpleados);

        jMenuClientes.setText("CLIENTES");
        jMenuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuClientes);

        jMenuCatalogos.setText("CATALOGO");

        jMenuDvd.setText("DVD");
        jMenuDvd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDvdActionPerformed(evt);
            }
        });
        jMenuCatalogos.add(jMenuDvd);

        jMenuVideos.setText("VIDEOS");
        jMenuVideos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVideosActionPerformed(evt);
            }
        });
        jMenuCatalogos.add(jMenuVideos);

        jMenu1.add(jMenuCatalogos);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(153, 255, 204));
        jMenu2.setText("SALIR");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEmpleadosActionPerformed

        EMPLEADOS ventana = new EMPLEADOS();
        jDesktopPane1.add(ventana);
              
                

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuEmpleadosActionPerformed

    private void jMenuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClientesActionPerformed

        CLIENTES ventana = new CLIENTES ();
         jDesktopPane1.add(ventana);


// TODO add your handling code here:
    }//GEN-LAST:event_jMenuClientesActionPerformed

    private void jMenuVideosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVideosActionPerformed
        // TODO add your handling code here:
        
      REGISTRO_VIDEOS ventana= new REGISTRO_VIDEOS ();
        jDesktopPane1.add(ventana);
        
    }//GEN-LAST:event_jMenuVideosActionPerformed

    private void jMenuDvdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDvdActionPerformed
 REGISTRO_DVD ventana= new REGISTRO_DVD ();
        jDesktopPane1.add(ventana);
        
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuDvdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PANTALLA_INICIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PANTALLA_INICIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PANTALLA_INICIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PANTALLA_INICIAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PANTALLA_INICIAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCatalogos;
    private javax.swing.JMenuItem jMenuClientes;
    private javax.swing.JMenuItem jMenuDvd;
    private javax.swing.JMenuItem jMenuEmpleados;
    private javax.swing.JMenuItem jMenuVideos;
    // End of variables declaration//GEN-END:variables
}
