/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LOGIN;

import FORMS.PANTALLA_INICIAL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Geovani
 */
public class LOGIN_SISTEMA_FM extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN_SISTEMA_FM
     */
    public LOGIN_SISTEMA_FM() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtPass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        FONDO1 = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NOMBRE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 80, 40));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 180, 30));

        txtSalir.setBackground(new java.awt.Color(51, 51, 51));
        txtSalir.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtSalir.setForeground(new java.awt.Color(255, 255, 255));
        txtSalir.setText("SALIR DEL SISTEMA");
        txtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalirActionPerformed(evt);
            }
        });
        getContentPane().add(txtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 190, 30));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 190, 30));
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 180, 30));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PASSWORD");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 100, 50));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("               LOGIN SISTEMA");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 230, 50));

        FONDO1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geovani\\Desktop\\SISTEMA_FM_INDIVIDUAL\\SISTEMA_FM\\FONDO1.jpg")); // NOI18N
        getContentPane().add(FONDO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 500));

        fondo2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Geovani\\Desktop\\SISTEMA_FM_INDIVIDUAL\\SISTEMA_FM\\fondo2.jpg")); // NOI18N
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 210, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalirActionPerformed

System.exit(0);        
// TODO add your handling code here:
    }//GEN-LAST:event_txtSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

if ( txtNombre.getText().isEmpty() || txtPass.getText().isEmpty()){
            
            JOptionPane.showMessageDialog(null, " NO SE PUEDE DEJAR CAMPOS VACIOS");
            
            txtNombre.setText("");
            txtPass.setText("");
        }
        else {
        try{
        
        Connection cn = DriverManager.getConnection("jdbc:mysql://localhost/SISTEMA_FM", "rex", "polloloco900");
        
        
        PreparedStatement pst = cn.prepareStatement("select * from  login where Usuario = ?");
        
        pst.setString(1, txtNombre.getText().trim());
        ResultSet rs = pst.executeQuery();
        
        PreparedStatement pst2 = cn.prepareStatement("select * from login where Pass = ?");
        
        pst2.setString(1, txtPass.getText().trim());
        ResultSet rs2 = pst2.executeQuery();
       
        if(rs.next()){
            
                if(rs2.next()){
                                JOptionPane.showMessageDialog(null, "Bienvenido" + "     " + rs.getString("Usuario"));
                                
                                
                PANTALLA_INICIAL Ventana= new PANTALLA_INICIAL();
                Ventana.setVisible(true);
                this.dispose();
                
                }
                        
            } else {
                JOptionPane.showMessageDialog(null, "ESTE USUARIO NO EXISTE");
                txtNombre.setText("");
                txtPass.setText("");
                
                
            }
        
        
        
        
      
        
        }catch(Exception e){
            
            
            
        }        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN_SISTEMA_FM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN_SISTEMA_FM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN_SISTEMA_FM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN_SISTEMA_FM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN_SISTEMA_FM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JButton txtSalir;
    // End of variables declaration//GEN-END:variables
}
